name: Release

on:
  push:
    tags:
      - 'v*'
      - '*dev*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Credentials
        uses: KasukuSakura/maven-center-publish@main
        with:
          credential: ${{ secrets.MVN_CENTERAL_CREDENTIAL }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build Project
        run: gradle build --info

      - name: Publish Modules
        run: gradle publish -x :kamiloply-gradle:publish --info

      - name: Publish Gradle Plugins
        run: >
          gradle
          publishPlugins --info
          -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
          -Pgradle.publish.key=${{    secrets.GRADLE_KEY    }}
